GESTION_DE_BILLET_beta2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('client.urls')),
    path('',include('dashboard.urls')),
    path('',include('companyman.urls')),
]

client/urls.py
from django.urls import path
from . import views

app_name="client"

urlpatterns = [
    path('',views.accueil_view,name='accueil'),
    path('suggestion/',views.suggestionForm,name='suggestion'),
    path('etape1/',views.reservation1_view,name='etape1'),
    path('listechoix/',views.listechoix_view,name='listechoix'),
    path('etape2/details/<int:billet_id>/',views.billet_detail_view,name='billet_detail_view'),
    path('etape2/<int:res_id>/',views.reservation2_view,name='etape2'),
    path('infoligne/<int:ln_id>/',views.infoligne_view, name='infoligne'),
    path('annulation1/',views.recherche1_view,name='annulation1'),
    path('annulation2/<int:billet_id>/',views.annulation_view,name='annulation2'),
    path('annulation3/<int:billet_id>/',views.annuler_billet,name='annulation3'),
    path('modification1/',views.recherche2_view,name='modification1'),
    path('modification2/<int:billet_id>/',views.modifier_billet,name='modification2'),
    path('compagnies/',views.lescompagnies_view,name='lescompagnies'),
    path('compagnie/<int:cp_id>/',views.lacompagnie_view, name='lacompagnie'),
]

templates/annulation1.html
<!DOCTYPE html>
{% extends 'base1.html' %}
{% load static %}

{% block contenu %}

<div class="bg-contact100">
    <h1 style="align-items: center;text-align: center; ">ETAPE 1 / RECHERCHE</h1>
    <div class="container-contact100">
        <div class="wrap-contact100">
            <div class="contact100-pic js-tilt" data-tilt>
                <img src="{% static 'images/modele-formulaire-inscription.avif' %}" alt="IMG">
            </div>
            <form class="contact100-form validate-form" method="post" action="">
                
                <span class="contact100-form-title">
                    <b>Tapez le code de votre billet ici</b> 
                </span>
                {% csrf_token %}
                <div class="wrap-input100 validate-input" data-validate="Un Nom est requi.">
                    {{ recherche.code_billet }}
                    <span class="focus-input100"></span>
                </div>
                
                <div class="container-contact100-form-btn">
                    <button class="contact100-form-btn" type="submit">
                        Rechercher
                    </button>
                </div>
                
            </form>
        </div>
    </div>
</div>
<script type="text/javascript"></script>
{% endblock contenu %}
    

templates/annulation2.html
<!DOCTYPE html>
{% extends 'base0.html' %}


{% block contenu %}
<div style="margin: auto;padding: auto; width: 1000px; font-size: 25px;">
    <h2>Billet de voyage
        <p>Ligne : {% if infoln %}{{ infoln.ligne_id.ville_dep.nom_ville }} -
            {{ infoln.ligne_id.ville_arr.nom_ville }}{% endif %}</p>
    </h2>
    <p><strong>Nom :</strong> {{ billet.nom_clt }}</p>
    <p><strong>Prénom :</strong> {{ billet.prenom_clt }}</p>
    <p><strong>Email :</strong> {{ billet.email_clt }}</p>
    <p><strong>Téléphone :</strong> {{ billet.telephone_clt }}</p>
    <p><strong>Code du billet :</strong> {{ billet.code_billet }}</p>
    <p><strong>Prix unitaire :</strong> {{ billet.prix }} francs CFA</p>
    <p><strong>Nombre de places :</strong> {{ billet.place }}</p>
    <p><strong>Montant total :</strong> {{ billet.montant_billet }} francs CFA</p>
    <p><strong>Etat du billet :</strong>
        {% if etat %}
        {{etat.libelle}}
        {% endif %}
    </p>
    <p><strong>Billet valide :</strong> {{billet.bl_valide}}</p>
    <p><strong>Date et heure de départ :</strong> {% if infoln %}{{ infoln.date_dep|date:"d-m-Y H:i:s" }}{% endif %}</p>
    <form method="post" action="{% url 'client:annulation3' billet.id %}">
        {% csrf_token %}
        <input type="hidden" name="billet_id" value="{{ billet.id }}">
        <button type="submit" class="btn btn-danger">Annuler le billet</button>
    </form><br>
    
    <footer><a class="btn" href="{% url 'client:annulation1' %} ">&laquo; Revenir en arrière</a></footer>
    
    <script>
      $(document).ready(function () {
        $('#tableau').DataTable({
            dom:'f',
            language: {
                url: "DataTables/media/french.json"},
        });
    });
    </script>
    </div>
{% endblock contenu %}
    

templates/base0.html
<!DOCTYPE html>
{% load static %}

{% load crispy_forms_tags %}

<html lang="fr">

<head>
  <title>
    {% block titre %}

    {% endblock titre %}
  </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="{% static 'layout.css' %}" type="text/css" media="all">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/framework.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap4/assets/css/docs.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap5/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap5/layout.css' %}">
  <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
  <script type="text/javascript" src="{% static 'bootstrap5/js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src=" {% static 'DataTables/media/js/jquery.js' %} "></script>
  <script type="text/javascript" src=" {% static 'DataTables/media/js/jquery.dataTables.min.js' %} "></script>
  <script type="text/javascript" src=" {% static 'DataTable/result.js' %} "></script>
  <link rel="stylesheet" type="text/css" href=" {% static 'DataTables/media/css/jquery.dataTables.min.css' %} ">

  {% block headcomplement %}

  {% endblock headcomplement %}



</head>

<body id="top">

  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->

  <div class="wrapper row0">

    <div id="topbar" class="hoc clear">
      <!-- ################################################################################################ -->
      <div class="fl_left">
        <ul>
          <li><i class="fa fa-phone"></i> +228 90 00 00 09</li>
          <li><i class="fa fa-envelope-o"></i> akstransport@gmail.com</li>
        </ul>
      </div>
      <!-- ################################################################################################ -->
    </div>
  </div>
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <div class="wrapper row1">
      <div class="wrapper bgded overlay" style="background-image:url('../images/demo/backgrounds/01.png');height: 5em;">
        <img src="{% static 'images/logo1.png' %}" alt="">
              {% now 'd/m/Y H:i:s' %}
  
      </div><br><br>  
    
    {% block contenu %}

    {% endblock contenu %}
  </div>
</body>

</html>

templates/base1.html
<!DOCTYPE html>
{% load static %}

{% load crispy_forms_tags %}

<html lang="fr">

<head>
  <title>
    {% block titre %}

    {% endblock titre %}
  </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="{% static 'layout.css' %}" type="text/css" media="all">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/framework.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap4/assets/css/docs.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap5/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap5/layout.css' %}">
  <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
  <!-- <script type="text/javascript" src=""></script> -->
  <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script> -->
  <script type="text/javascript" src="{% static 'bootstrap5/js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src=" {% static 'DataTables/media/js/jquery.js' %} "></script>
  <script type="text/javascript" src=" {% static 'DataTables/media/js/jquery.dataTables.min.js' %} "></script>
  <script type="text/javascript" src=" {% static 'DataTable/result.js' %} "></script>
  <link rel="stylesheet" type="text/css" href=" {% static 'DataTables/media/css/jquery.dataTables.min.css' %} ">

  {% block headcomplement %}

  {% endblock headcomplement %}



</head>

<body oncontextmenu="return false" class="snippet-body">
    <div class="wrapper row0">

        <div id="topbar" class="hoc clear">
          <!-- ################################################################################################ -->
          <div class="fl_left">
            <ul>
              <li><i class="fa fa-phone"></i> +228 90 00 00 09</li>
              <li><i class="fa fa-envelope-o"></i> akstransport@gmail.com</li>
            </ul>
          </div>
          <!-- ################################################################################################ -->
        </div>
      </div>
      <!-- ################################################################################################ -->
      <!-- ################################################################################################ -->
      <!-- ################################################################################################ -->
      <div class="wrapper row1">
        <header id="header" class="hoc clear">
          <!-- ################################################################################################ -->
          <div id="logo" class="fl_left">
            <img src="{% static 'images/logo1.png' %}" alt="">
            {% now 'd/m/Y H:i:s' %}
          </div>
    
          <!-- ################################################################################################ -->
        </header>
        {% block contenu %}
    
        {% endblock contenu %}
      </div>
</body>

</html> 

templates/billet_detail.html
<!DOCTYPE html>
{% extends 'base0.html' %}


{% block contenu %}
<div style="margin: auto;padding: auto; width: 1000px;">
    <h2>Billet de voyage 
        <p>Ligne : {% if infoln %}{{ infoln.ligne_id.ville_dep.nom_ville }} - 
            {{ infoln.ligne_id.ville_arr.nom_ville }}{% endif %}</p> 
    </h2>
    <p><strong>Nom :</strong> {{ billet.nom_clt }}</p>
    <p><strong>Prénom :</strong> {{ billet.prenom_clt }}</p>
    <p><strong>Email :</strong> {{ billet.email_clt }}</p>
    <p><strong>Téléphone :</strong> {{ billet.telephone_clt }}</p>
    <p><strong>Code du billet :</strong> {{ billet.code_billet }}</p>
    <p><strong>Prix unitaire :</strong> {{ billet.prix }} francs CFA</p>
    <p><strong>Nombre de places :</strong> {{ billet.place }}</p>
    <p><strong>Montant total :</strong> {{ billet.montant_billet }} francs CFA</p>
    <p><strong>Etat du billet :</strong>
        {{billet.etat_billet.libelle}}
    </p>
    <p><strong>Billet valide :</strong> {{billet.bl_valide}}</p>
    <p><strong>Date et heure de départ :</strong> {% if infoln %}{{ infoln.date_dep|date:"d-m-Y H:i:s" }}{% endif %}</p>
    
    <footer><a class="btn" href="{% url 'client:accueil' %} ">&laquo; Revenir en arrière</a></footer>
    <script>
      $(document).ready(function () {
        $('#tableau').DataTable({
            dom:'f',
            language: {
                url: "DataTables/media/french.json"},
        });
    });
    </script>
    </div>
{% endblock contenu %}

templates/infoligne.html
<!DOCTYPE html>
{% extends 'base0.html' %}


{% block contenu %}
<div style="margin: auto;padding: auto; width: 1000px;">
  
    
    <caption><h4>LIGNE : {{ln.ville_dep.nom_ville}} - {{ln.ville_arr.nom_ville}}</h4> </caption>
    
    <div class="scrollable">
      <table id="tableau" class="display">
        <thead>
          <tr>
            <th>DATE ET HEURE DE DEPART</th>
            <th>COMPAGNIE</th>
            <th>PRIX (CFA)</th>
            <th>PLACES DISPONIBLE</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        {% for i in infln %}    
          <tr>
            <td> {{i.date_dep}} </td>
            <td> {{ i.bus_id.compagnie_id.nom_cp }} </td>
            <td> {{i.prix}} </td>
            <td> {{i.bus_id.nb_place}} </td>
            <td>
              <footer><a class="btn" href="{% url 'client:etape2' i.id %}">Réserver &rsaquo;</a></footer>
            </td>
          </tr>
          {% endfor %}
    
        </tbody>
      </table>
    </div>
    <footer><a class="btn" href="{% url 'client:accueil' %} ">&laquo; Revenir en arrière</a></footer>
    <script>
      $(document).ready(function () {
        $('#tableau').DataTable({
            dom:'f',
            language: {
                url: "DataTables/media/french.json"},
        });
    });
    </script>
    </div>
{% endblock contenu %}
    

templates/listechoix.html
<!DOCTYPE html>
{% extends 'base0.html' %}


{% block contenu %}
<div class="top">

  <!-- ################################################################################################ -->
  <div class="wrapper row3">
    <main class="hoc container clear">
      <!-- main body -->
      <!-- ################################################################################################ -->
      <div class="sidebar one_quarter first">
        <!-- ################################################################################################ -->
        <h6>Liste des lignes disponibles</h6><br>
        <nav class="sdb_holder">
          <ul>

            {% for i in lignes %}
            <li>{{i.ville_dep.nom_ville}} - {{i.ville_arr.nom_ville}}</li>
            {% endfor %}
          </ul>
        </nav>
      </div>
      <!-- ################################################################################################ -->
      <!-- ################################################################################################ -->
      <div class="content three_quarter">
        <!-- ################################################################################################ -->
        <h1>Liste des voyages</h1>
        <!-- ################################################################################################ -->
        <h2  class="heading">Comment faire ?</h2>
        <img class="imgr borderedbox inspace-5" src="../images/demo/imgr.gif" alt="">
        <p>Aliquatjusto quisque nam consequat doloreet vest orna partur scetur portortis nam. Metadipiscing eget facilis
          elit sagittis felisi eger id justo maurisus convallicitur.</p>
        <p>Dapiensociis <a href="#">temper donec auctortortis cumsan</a> et curabitur condis lorem loborttis leo.
          Ipsumcommodo libero nunc at in velis tincidunt pellentum tincidunt vel lorem.</p>
        <img class="imgl borderedbox inspace-5" src="../images/demo/imgl.gif" alt="">
        <p>This is a W3C compliant free website template from <a href="https://www.os-templates.com/"
            title="Free Website Templates">OS Templates</a>. For full terms of use of this template please read our <a
            href="https://www.os-templates.com/template-terms">website template licence</a>.</p>
        <p>You can use and modify the template for both personal and commercial use. You must keep all copyright
          information and credit links in the template and associated files. For more website templates visit our <a
            href="https://www.os-templates.com/">free website templates</a> section.</p>
        <p>Portortornec condimenterdum eget consectetuer condis consequam pretium pellus sed mauris enim. Puruselit
          mauris nulla hendimentesque elit semper nam a sapien urna sempus.</p><br><br>
        <h1  class="heading">Choisissez votre ligne</h1>

      </div>
    </main>
  </div>
  <div class="scrollable">
    <div style="margin: auto;padding: auto; width: 1100px;">


      <!-- <caption>
        <h4>Choisissez votre ligne</h4>
      </caption> -->

      <!-- <div class="scrollable"> -->
      <table id="tableau" class="display">
        <thead>
          <tr>
            <th>DATE ET HEURE DE DEPART</th>
            <th>LIGNE</th>
            <th>COMPAGNIE</th>
            <th>PRIX (CFA)</th>
            <th>PLACES DISPONIBLE</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for i in infln %}
          <tr>
            <td> {{i.date_dep}} </td>
            <td>{{i.ligne_id.ville_dep.nom_ville}} - {{i.ligne_id.ville_arr.nom_ville}}</td>
            <td> {{ i.bus_id.compagnie_id.nom_cp }} </td>
            <td> {{i.prix}} </td>
            <td> {{i.bus_id.nb_place}} </td>
            <td>
              <footer><a class="btn" href="{% url 'client:etape2' i.id %}">Réserver &rsaquo;</a></footer>
            </td>
          </tr>
          {% endfor %}

        </tbody>
      </table>
    </div>
  </div>
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <footer><a class="btn" href="{% url 'client:accueil' %} ">&laquo; Revenir en arrière</a></footer>
  <script>
    $(document).ready(function () {
      $('#tableau').DataTable({
        dom: 'f',
        language: {
          url: "DataTables/media/french.json"
        },
      });
    });
  </script>
</div>
{% endblock contenu %}

templates/modification1.html
<!DOCTYPE html>
{% extends 'base1.html' %}
{% load static %}

{% block contenu %}

<div class="bg-contact100">
    <h1 style="align-items: center;text-align: center; ">MODIFICATION DE BILLET / ETAPE 1</h1>
    <div class="container-contact100">
        <div class="wrap-contact100">
            <div class="contact100-pic js-tilt" data-tilt>
                <img src="{% static 'images/modele-formulaire-inscription.avif' %}" alt="IMG">
            </div>
            <form class="contact100-form validate-form" method="post" action="">
                
                <span class="contact100-form-title">
                    <b>Saisissez le code de votre billet ici</b> 
                </span>
                {% csrf_token %}
                <div class="wrap-input100 validate-input" data-validate="Un Nom est requi.">
                    {{ recherche.code_billet }}
                    <span class="focus-input100"></span>
                </div>
                
                <div class="container-contact100-form-btn">
                    <button class="contact100-form-btn" type="submit">
                        Rechercher
                    </button>
                </div>
                
            </form>
        </div>
    </div>
</div>
<script type="text/javascript"></script>
{% endblock contenu %}
    

templates/modification2.html
<!DOCTYPE html>
{% extends 'base1.html' %}
{% load static %}

{% block contenu %}

<div class="bg-contact100">
    <h1 style="align-items: center;text-align: center; ">RESERVATION</h1>
    <div class="container-contact100">
        <div class="wrap-contact100">
            <div class="contact100-pic js-tilt" data-tilt>
                <img src="{% static 'images/modele-formulaire-inscription.avif' %}" alt="IMG">
            </div>
            <form class="contact100-form validate-form" method="post" action="">
                
                <span class="contact100-form-title">
                    <b>Formulaire de modification de billet</b> 
                </span>
                {% csrf_token %}
                <div class="wrap-input100 validate-input" data-validate="Un Nom est requi.">
                    {{ form.nom_clt }}
                    <span class="focus-input100"></span>
                </div>
                <div class="wrap-input100 validate-input" data-validate="Un Prénom est requi">
                    {{ form.prenom_clt }}
                    <span class="focus-input100"></span>
                </div>
                <div class="wrap-input100 validate-input" data-validate="Un email valide est requi.">
                    {{ form.email_clt }}
                    <span class="focus-input100"></span>
                </div>
                <div class="wrap-input100 validate-input" data-validate="Un numéro de telephone valide est requi">
                    {{ form.telephone_clt }}
                    <span class="focus-input100"></span>
                </div>
                <div class="wrap-input100 validate-input" data-validate="Vous devez selectionner le nombre de place">
                    {{ form.place }}
                    <span class="focus-input100"></span>
                </div>
                <div class="wrap-input100 validate-input" data-validate="Vous devez selectionner le nombre de place">
                    {{ form.date_dep }}
                    <span class="focus-input100"></span>
                </div>
                <div class="container-contact100-form-btn">
                    <button class="contact100-form-btn" type="submit">
                        Valider les modifications
                    </button>
                </div>
                
            </form>
        </div>
    </div>
</div>
<script type="text/javascript"></script>
{% endblock contenu %}
    

templates/reservation_etape1.html
<!DOCTYPE html>
{% extends 'base0.html' %}


{% block contenu %}

<p></p>
<div style="margin: auto;padding: auto; width: 1000px;">
  <p>ETAPE N°1 : CHOIX DU PLAN DE VOYAGE</p>
    <caption><h1>{{ rdt.date_dep }}</h1></caption>
    
    
    <div class="scrollable">
      <table id="tableau" class="display">
        <thead>
          <tr>
            <th>LIGNE</th>
            <th>DATE ET HEURE DE DEPART</th>
            <th>COMPAGNIE</th>
            <th>PRIX (CFA)</th>
            <th>PLACES DISPONIBLE</th>
            <th>DECISION</th>
          </tr>
        </thead>
        <tbody>
        {% for i in infln %}    
          <tr>
            <td> {{i.ligne_id.ville_dep.ville_id.nom_ville}} - {{i.ligne_id.ville_arr.ville_id.nom_ville}} </td>
            <td> {{i.date_dep}} </td>
            <td> {{ i.bus_id.compagnie_id.nom_cp }} </td>
            <td> {{i.prix}} </td>
            <td> {{i.bus_id.nb_place}} </td>
            <td>
              <footer><a class="btn" href="{% url 'client:etape2' %}">Choisir &rsaquo;</a></footer>
            </td>
          </tr>
          {% endfor %}
    
        </tbody>
      </table>
    </div>
    <footer><a class="btn" href="{% url 'client:accueil' %} ">&laquo; Revenir en arrière</a></footer>
    
    <script>
      $(document).ready(function () {
        $('#tableau').DataTable({
            dom:'f',
            language: {
                url: "DataTables/media/french.json"},
        });
    });
    </script>
    </div>
{% endblock contenu %}
    

templates/reservation_etape3.html
<!DOCTYPE html>
{% extends 'base1.html' %}
{% load static %}

{% block contenu %}

<div class="bg-contact100">
    <h1 style="align-items: center;text-align: center; ">Votre Billet : </h1>
    <div class="container-contact100">
        <div class="wrap-contact100">
           
            {{instance}}
          
        </div>
    </div>
</div>
<script type="text/javascript"></script>
{% endblock contenu %}
    

templates/suggestion.html
<!DOCTYPE html>
{% extends 'base0.html' %}


{% block titre %}
AKS-T | Suggestions
{% endblock titre %}

{% block headcomplement %}
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script> -->
{% endblock headcomplement %}

{% block contenu %}

<div class="bg-contact100">
    <h1 style="align-items: center;text-align: center; ">SUGGESTIONS</h1>
    <div class="container-contact100">
        <div class="wrap-contact100">
            <div class="contact100-pic js-tilt" data-tilt>
                <img src="https://i.imgur.com/VRFiMzM.png" alt="IMG">
            </div>
            <form class="contact100-form validate-form" method="post">
                
                <span class="contact100-form-title">
                   Faites nous part de vos <b>suggestions</b> 
                </span>
                {% csrf_token %}
                <div class="wrap-input100 validate-input" data-validate="Un email valide est requi. Exemple: ex@abc.xyz">
                    
                    {{ form.email }}
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                    </span>
                </div>
                <p class="input100">Destiné à :</p>
                <div class="wrap-input100 validate-input" data-validate="">
                    
                    {{ form.destinataire }}
                    <span class="focus-input100"></span> 

                </div>
                
                <div class="wrap-input100 validate-input" data-validate="Un message est requi">
                    {{ form.message }}
                    <span class="focus-input100"></span>
                </div>
                <div class="container-contact100-form-btn">
                    <button class="contact100-form-btn">
                        Envoyer
                    </button>
                </div>
                
            </form>
        </div>
        <div class="container-contact100-form-btn" style="width: 45%;">
            <button class="contact100-form-btn">
                <a class="contact100-form-btn" href="{% url 'client:accueil' %} ">&laquo; Revenir à la page d'accueil</a>
            </button>
        </div>
    </div>
</div>
<script type="text/javascript"></script>


{% endblock contenu %}